[package]
name = "dice_roller"
version = "0.1.0"
authors = ["AurelienLP <aurelien.laporte@canaltp.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
